<?php 
//pages
$pages = array();
$pages[] = array(
	'title' => 'Page 01',
	'content' => 'This is page 01 content'
);

$pages[] = array(
	'title' => 'Page 02',
	'content' => 'This is page 02 content'
);



//Testimonials category
$testimonials = array();
$testimonials[] = 'Testimonial 01';
$testimonials[] = "Testimonial 02";


//Nav menu
$nav_menu = array(
			'name' => 'Primary Menu',
			'theme_location' => 'primary-menu'
		);
